apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-aggregator
spec:
  schedule: "0 0 * * *"  # Run daily at midnight
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: aggregator
              image: gcr.io/${GKE_PROJECT}/aggregator_service:latest
              env:
                - name: MONGO_URL
                  valueFrom:
                    secretKeyRef:
                      name: healthsync-secrets
                      key: mongo-url
                - name: REDSHIFT_HOST
                  valueFrom:
                    secretKeyRef:
                      name: healthsync-secrets
                      key: redshift-host
                - name: REDSHIFT_USER
                  valueFrom:
                    secretKeyRef:
                      name: healthsync-secrets
                      key: redshift-user
                - name: REDSHIFT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: healthsync-secrets
                      key: redshift-password
          restartPolicy: OnFailure
