name: Build and Deploy to GKE (Blue-Green)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: meditrack-cluster
  GKE_ZONE: us-central1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [appointment_service, notification_service, patient_service]
        include:
          - service: appointment_service
            port: 8003
            image_name: appointment-service

          - service: notification_service
            port: 8004
            image_name: notification-service

          - service: patient_service
            port: 8001
            image_name: patient-service


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Configure Docker
        run: gcloud --quiet auth configure-docker

      - name: Configure kubectl
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Create Kubernetes Secrets
        run: |
          kubectl create secret generic healthsync-secrets \
            --from-literal=mongo-url=${{ secrets.MONGO_URL }} \
            --from-literal=redshift-host=${{ secrets.REDSHIFT_HOST }} \
            --from-literal=redshift-user=${{ secrets.REDSHIFT_USER }} \
            --from-literal=redshift-password=${{ secrets.REDSHIFT_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Build and Push Docker Image
        run: |
          echo "Building and pushing image for service: ${{ matrix.service }}"
          docker build \
            --tag "gcr.io/$PROJECT_ID/${{ matrix.image_name }}:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            services/${{ matrix.service }}
          docker push "gcr.io/$PROJECT_ID/${{ matrix.image_name }}:$GITHUB_SHA"

      - name: Deploy Green Environment
        run: |
          echo "Deploying Green environment for service: ${{ matrix.service }}"
          sed -i "s|gcr.io/$PROJECT_ID/${{ matrix.image_name }}:latest|gcr.io/$PROJECT_ID/${{ matrix.image_name }}:$GITHUB_SHA|" \
            kubernetes/blue-green/deployment-green.yaml
          kubectl apply -f kubernetes/blue-green/deployment-green.yaml

      - name: Test Green Environment
        run: |
          echo "Testing Green environment for service: ${{ matrix.service }}"
          curl -s http://34.41.192.165:8003/health || exit 1

      - name: Switch Traffic to Green
        run: |
          echo "Switching traffic to Green environment for service: ${{ matrix.service }}"
          kubectl patch service ${{ matrix.service }} \
            -p '{"spec":{"selector":{"version":"green"}}}'

      - name: Remove Blue Deployment
        if: success()
        run: |
          echo "Removing Blue environment for service: ${{ matrix.service }}"
          kubectl delete deployment ${{ matrix.image_name }}-blue

      - name: Rollback to Blue
        if: failure()
        run: |
          echo "Rolling back to Blue environment for service: ${{ matrix.service }}"
          kubectl patch service ${{ matrix.service }} \
            -p '{"spec":{"selector":{"version":"blue"}}}'

      - name: Deploy Aggregator CronJob
        run: |
          echo "Building and deploying aggregator service"
          docker build \
            -t "gcr.io/$PROJECT_ID/aggregator_service:$GITHUB_SHA" \
            services/aggregator_service
          docker push "gcr.io/$PROJECT_ID/aggregator_service:$GITHUB_SHA"
          sed -i "s|gcr.io/$PROJECT_ID/aggregator_service:latest|gcr.io/$PROJECT_ID/aggregator_service:$GITHUB_SHA|" \
            kubernetes/aggregator_service/cronjob.yaml
          kubectl apply -f kubernetes/aggregator_service/cronjob.yaml
